@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'GSO for table item-data to be processed'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity /ZUORA001/I_BL_IG
  as select from /zuora001/t_bl_i
  association to parent /ZUORA001/I_BL_HG as _CREATORDATAIN on  $projection.JeUid      = _CREATORDATAIN.JeUid
                                                            and $projection.CustomerId = _CREATORDATAIN.CustomerId
{
  key je_uid             as JeUid,
  key customer_id        as CustomerId,
  key bl_doc_number      as BlDocNumber,
      destination_system as DestinationSystem,
      destination_name   as DestinationName,
      land_scape         as LandScape,
      salesorg           as Salesorg,
      distr_chan         as DistrChan,
      division           as Division,
      doc_type           as DocType,
      ordbilltyp         as Ordbilltyp,
      bill_date          as BillDate,
      sold_to            as SoldTo,
      item_categ         as ItemCateg,
      acctasgnmt         as Acctasgnmt,
      price_date         as PriceDate,
      country            as Country,
      plant              as Plant,
      bill_to            as BillTo,
      payer              as Payer,
      ship_to            as ShipTo,
      ref_doc            as RefDoc,
      material           as Material,
      req_qty            as ReqQty,
      currency           as Currency,
      short_text         as ShortText,
      taxcl_1mat         as Taxcl1mat,
      ref_item           as RefItem,
      stat_group         as StatGroup,
      no_matmast         as NoMatmast,
      addr_no            as AddrNo,
      title              as Title,
      name               as Name,
      name_2             as Name2,
      postl_code         as PostlCode,
      consumctry         as Consumctry,
      city               as City,
      district           as District,
      street             as Street,
      region             as Region,
      prod_hier          as ProdHier,
      sales_unit         as SalesUnit,
      profit_ctr         as ProfitCtr,
      taxjurcode         as Taxjurcode,
      purch_ord          as PurchOrd,
      doc_number         as DocNumber,
      itm_number         as ItmNumber,
      origindoc          as Origindoc,
      item               as Item,
      created_by         as CreatedBy,
      material_external  as MaterialExternal,
      material_guid      as MaterialGuid,
      material_version   as MaterialVersion,
      incoterms1         as Incoterms1,
      incoterms2         as Incoterms2,
      exchange_rate      as ExchangeRate,
      payment_terms      as PaymentTerms,
      hg_lv_item         as HgLvItem,
      ref_doc_ca         as RefDocCa,
      orderid            as Orderid,
      profit_segm_no     as ProfitSegmNo,
      costcenter         as Costcenter,
      wbs_elem           as WbsElem,
      tax_depart_cty     as TaxDepartCty,
      tax_dest_cty       as TaxDestCty,
      serv_date          as ServDate,
      cont_acct          as ContAcct,
      parallel_qty       as ParallelQty,
      parallel_uom       as ParallelUom,
      ref_doc_ca_long    as RefDocCaLong,
      incotermsv         as Incotermsv,
      incoterms2l        as Incoterms2l,
      incoterms3l        as Incoterms3l,
      material_long      as MaterialLong,

      _CREATORDATAIN
}
