@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: '/ZUORA001/R_BL_I'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity /ZUORA001/C_BL_I as projection on /ZUORA001/R_BL_I
{
  key je_uid,
  key customer_id,
  key Itemnobcc,
    bl_doc_number,
    destination_system,
    destination_name,   
    SALESORG,
    DISTR_CHAN,
    DIVISION,
    DOC_TYPE,
    ORDBILLTYP,
    BILL_DATE,
    SOLD_TO,
    ITEM_CATEG,
    ACCTASGNMT,
    PRICE_DATE,
    COUNTRY,
    PLANT,
    BILL_TO,
    PAYER,
    SHIP_TO,
    REF_DOC,
    MATERIAL,
    REQ_QTY,
    CURRENCY,
    SHORT_TEXT,
    TAXCL_1MAT,
    REF_ITEM,
    STAT_GROUP,
    NO_MATMAST,
    ADDR_NO,
    TITLE,
    NAME,
    NAME_2,
    POSTL_CODE,
    CONSUMCTRY,
    CITY,
    DISTRICT,
    STREET,
    REGION,
    PROD_HIER,
    SALES_UNIT,
    PROFIT_CTR,
    TAXJURCODE,
    PURCH_ORD,
    DOC_NUMBER,
    ITM_NUMBER,
    ORIGINDOC,
    ITEM,
    CREATED_BY,
    MATERIAL_EXTERNAL,
    MATERIAL_GUID,
    MATERIAL_VERSION,
    INCOTERMS1,
    INCOTERMS2,
    EXCHANGE_RATE,
    PAYMENT_TERMS,
    HG_LV_ITEM,
    REF_DOC_CA,
    ORDERID,
    PROFIT_SEGM_NO,
    COSTCENTER,
    WBS_ELEM,
    TAX_DEPART_CTY,
    TAX_DEST_CTY,
    SERV_DATE,
    CONT_ACCT,
    PARALLEL_QTY,
    PARALLEL_UOM,
    REF_DOC_CA_LONG,
    INCOTERMSV,
    INCOTERMS2L,
    INCOTERMS3L,
    MATERIAL_LONG,
    CREATORDATAIN: redirected to parent /ZUORA001/C_BL_H
}
