@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Projection on GSO item-data to be prcsd'
@Metadata.ignorePropagatedAnnotations: true
define view entity /ZUORA001/C_BL_IG
  as projection on /ZUORA001/I_BL_IG
{
  key JeUid,
  key CustomerId,
  key BlDocNumber,
      DestinationSystem,
      DestinationName,
      LandScape,
      Salesorg,
      DistrChan,
      Division,
      DocType,
      Ordbilltyp,
      BillDate,
      SoldTo,
      ItemCateg,
      Acctasgnmt,
      PriceDate,
      Country,
      Plant,
      BillTo,
      Payer,
      ShipTo,
      RefDoc,
      Material,
      ReqQty,
      Currency,
      ShortText,
      Taxcl1mat,
      RefItem,
      StatGroup,
      NoMatmast,
      AddrNo,
      Title,
      Name,
      Name2,
      PostlCode,
      Consumctry,
      City,
      District,
      Street,
      Region,
      ProdHier,
      SalesUnit,
      ProfitCtr,
      Taxjurcode,
      PurchOrd,
      DocNumber,
      ItmNumber,
      Origindoc,
      Item,
      CreatedBy,
      MaterialExternal,
      MaterialGuid,
      MaterialVersion,
      Incoterms1,
      Incoterms2,
      ExchangeRate,
      PaymentTerms,
      HgLvItem,
      RefDocCa,
      Orderid,
      ProfitSegmNo,
      Costcenter,
      WbsElem,
      TaxDepartCty,
      TaxDestCty,
      ServDate,
      ContAcct,
      ParallelQty,
      ParallelUom,
      RefDocCaLong,
      Incotermsv,
      Incoterms2l,
      Incoterms3l,
      MaterialLong,
      /* Associations */
      _CREATORDATAIN : redirected to parent /ZUORA001/C_BL_HG
}
