@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Journal Entry - Vendor Projection'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity /ZUORA001/C_JE_V as projection on /ZUORA001/R_JE_V
{
    key je_uid,
    key customer_id,
    key JeDocNumber,
    DestinationSystem,
    DestinationName,
    ItemnoAcc,
    VendorNo,
    GlAccount,
    RefKey1,
    RefKey2,
    RefKey3,
    CompCode,
    BusArea,
    Pmnttrms,
    BlineDate,
    DsctDays1,
    DsctDays2,
    Netterms,
    DsctPct1,
    DsctPct2,
    PymtMeth,
    Pmtmthsupl,
    PmntBlock,
    ScbankInd,
    Supcountry,
    SupcountryIso,
    BllsrvInd,
    AllocNmbr,
    ItemText,
    PoSubNo,
    PoCheckdg,
    PoRefNo,
    PymtCurIso,
    SpGlInd,
    TaxCode,
    TaxDate,
    Taxjurcode,
    AltPayee,
    AltPayeeBank,
    PartnerBk,
    BankId,
    PartnerGuid,
    ProfitCtr,
    Fund,
    WTaxCode,
    Businessplace,
    Sectioncode,
    Instr1,
    Instr2,
    Instr3,
    Instr4,
    Branch,
    PymtCur,
    PymtAmt,
    GrantNbr,
    Measure,
    Housebankacctid,
    BudgetPeriod,
    PpaExInd,
    PartBusinessplace,
    Housebank,
    Housebankaccount,
    /* Associations */
    DOCUMENTHEADER : redirected to parent /ZUORA001/C_JE_H
}
