@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Journal Entry Item View'
@Metadata.ignorePropagatedAnnotations: true
/*+[hideWarning] { "IDS" : [ "KEY_CHECK" ]  } */
define view entity /ZUORA001/R_JE_I as select from /zuora001/t_je_i
association to parent /ZUORA001/R_JE_H as DOCUMENTHEADER
    on $projection.je_uid = DOCUMENTHEADER.je_uid
    and $projection.customer_id =  DOCUMENTHEADER.customer_id
    and $projection.JeDocNumber =  DOCUMENTHEADER.JeDocNumber
{
    key je_uid as je_uid,
    key customer_id  as customer_id,
    key je_doc_number as JeDocNumber,
    key itemno_acc as ItemnoAcc,
    destination_system as destination_system,
    destination_name   as destination_name,
    gl_account as GlAccount,
    item_text as ItemText,
    stat_con as StatCon,
    log_proc as LogProc,
    ac_doc_no as AcDocNo,
    ref_key_1 as RefKey1,
    ref_key_2 as RefKey2,
    ref_key_3 as RefKey3,
    acct_key as AcctKey,
    acct_type as AcctType,
    doc_type as DocType,
    comp_code as CompCode,
    bus_area as BusArea,
    func_area as FuncArea,
    plant as Plant,
    fis_period as FisPeriod,
    fisc_year as FiscYear,
    pstng_date as PstngDate,
    value_date as ValueDate,
    fm_area as FmArea,
    customer as Customer,
    cshdis_ind as CshdisInd,
    vendor_no as VendorNo,
    alloc_nmbr as AllocNmbr,
    tax_code as TaxCode,
    taxjurcode as Taxjurcode,
    ext_object_id as ExtObjectId,
    bus_scenario as BusScenario,
    costobject as Costobject,
    costcenter as Costcenter,
    acttype as Acttype,
    profit_ctr as ProfitCtr,
    part_prctr as PartPrctr,
    network as Network,
    wbs_element as WbsElement,
    orderid as Orderid,
    order_itno as OrderItno,
    routing_no as RoutingNo,
    activity as Activity,
    cond_type as CondType,
    cond_count as CondCount,
    cond_st_no as CondStNo,
    fund as Fund,
    funds_ctr as FundsCtr,
    cmm_item as CmmItem,
    co_busproc as CoBusproc,
    asset_no as AssetNo,
    sub_number as SubNumber,
    bill_type as BillType,
    sales_ord as SalesOrd,
    s_ord_item as SOrdItem,
    distr_chan as DistrChan,
    division as Division,
    salesorg as Salesorg,
    sales_grp as SalesGrp,
    sales_off as SalesOff,
    sold_to as SoldTo,
    de_cre_ind as DeCreInd,
    p_el_prctr as PElPrctr,
    xmfrw as Xmfrw,
    quantity as Quantity,
    base_uom as BaseUom,
    base_uom_iso as BaseUomIso,
    inv_qty as InvQty,
    inv_qty_su as InvQtySu,
    sales_unit as SalesUnit,
    sales_unit_iso as SalesUnitIso,
    po_pr_qnt as PoPrQnt,
    po_pr_uom as PoPrUom,
    po_pr_uom_iso as PoPrUomIso,
    entry_qnt as EntryQnt,
    entry_uom as EntryUom,
    entry_uom_iso as EntryUomIso,
    volume as Volume,
    volumeunit as Volumeunit,
    volumeunit_iso as VolumeunitIso,
    gross_wt as GrossWt,
    net_weight as NetWeight,
    unit_of_wt as UnitOfWt,
    unit_of_wt_iso as UnitOfWtIso,
    item_cat as ItemCat,
    material as Material,
    matl_type as MatlType,
    mvt_ind as MvtInd,
    reval_ind as RevalInd,
    orig_group as OrigGroup,
    orig_mat as OrigMat,
    serial_no as SerialNo,
    part_acct as PartAcct,
    tr_part_ba as TrPartBa,
    trade_id as TradeId,
    val_area as ValArea,
    val_type as ValType,
    asval_date as AsvalDate,
    po_number as PoNumber,
    po_item as PoItem,
    itm_number as ItmNumber,
    cond_category as CondCategory,
    func_area_long as FuncAreaLong,
    cmm_item_long as CmmItemLong,
    grant_nbr as GrantNbr,
    cs_trans_t as CsTransT,
    measure as Measure,
    segment as Segment,
    partner_segment as PartnerSegment,
    res_doc as ResDoc,
    res_item as ResItem,
    billing_period_start_date as BillingPeriodStartDate,
    billing_period_end_date as BillingPeriodEndDate,
    ppa_ex_ind as PpaExInd,
    fastpay as Fastpay,
    partner_grant_nbr as PartnerGrantNbr,
    budget_period as BudgetPeriod,
    partner_budget_period as PartnerBudgetPeriod,
    partner_fund as PartnerFund,
    itemno_tax as ItemnoTax,
    payment_type as PaymentType,
    expense_type as ExpenseType,
    program_profile as ProgramProfile,
    material_long as MaterialLong,
    housebank as Housebank,
    housebankaccount  as Housebankaccount        ,
    pmnttrms as PaymentTerms,
    DOCUMENTHEADER 
}
