@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Root View for Journal Item'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity /ZUORA001/C_JE_I
  as projection on /ZUORA001/R_JE_I
{
  key je_uid,
  key customer_id,
  key JeDocNumber,
  key ItemnoAcc,
      destination_system,
      destination_name,      
      GlAccount,
      ItemText,
      StatCon,
      LogProc,
      AcDocNo,
      RefKey1,
      RefKey2,
      RefKey3,
      AcctKey,
      AcctType,
      DocType,
      CompCode,
      BusArea,
      FuncArea,
      Plant,
      FisPeriod,
      FiscYear,
      PstngDate,
      ValueDate,
      FmArea,
      Customer,
      CshdisInd,
      VendorNo,
      AllocNmbr,
      TaxCode,
      Taxjurcode,
      ExtObjectId,
      BusScenario,
      Costobject,
      Costcenter,
      Acttype,
      ProfitCtr,
      PartPrctr,
      Network,
      WbsElement,
      Orderid,
      OrderItno,
      RoutingNo,
      Activity,
      CondType,
      CondCount,
      CondStNo,
      Fund,
      FundsCtr,
      CmmItem,
      CoBusproc,
      AssetNo,
      SubNumber,
      BillType,
      SalesOrd,
      SOrdItem,
      DistrChan,
      Division,
      Salesorg,
      SalesGrp,
      SalesOff,
      SoldTo,
      DeCreInd,
      PElPrctr,
      Xmfrw,
      Quantity,
      BaseUom,
      BaseUomIso,
      InvQty,
      InvQtySu,
      SalesUnit,
      SalesUnitIso,
      PoPrQnt,
      PoPrUom,
      PoPrUomIso,
      EntryQnt,
      EntryUom,
      EntryUomIso,
      Volume,
      Volumeunit,
      VolumeunitIso,
      GrossWt,
      NetWeight,
      UnitOfWt,
      UnitOfWtIso,
      ItemCat,
      Material,
      MatlType,
      MvtInd,
      RevalInd,
      OrigGroup,
      OrigMat,
      SerialNo,
      PartAcct,
      TrPartBa,
      TradeId,
      ValArea,
      ValType,
      AsvalDate,
      PoNumber,
      PoItem,
      ItmNumber,
      CondCategory,
      FuncAreaLong,
      CmmItemLong,
      GrantNbr,
      CsTransT,
      Measure,
      Segment,
      PartnerSegment,
      ResDoc,
      ResItem,
      BillingPeriodStartDate,
      BillingPeriodEndDate,
      PpaExInd,
      Fastpay,
      PartnerGrantNbr,
      BudgetPeriod,
      PartnerBudgetPeriod,
      PartnerFund,
      ItemnoTax,
      PaymentType,
      ExpenseType,
      ProgramProfile,
      MaterialLong,
       Housebank,
       Housebankaccount,
      /* Associations */
      DOCUMENTHEADER : redirected to parent /ZUORA001/C_JE_H
}
